### ISSUE TITLE
Tracing

### ISSUE THREAD

**Issue by amy-keibler** [game-night-dot-gay/game-night#5]
- [x] set up Honeycomb accounts
- [x] set up tracing + opentelemetry connection to honeycomb
  - [x] add app_config for Honeycomb endpoint and API key

**Reference:**
- [tracing-opentelemetry](https://crates.io/crates/tracing-opentelemetry/0.17.3) 
- [Crate docs](https://docs.rs/tracing-opentelemetry/0.17.3/tracing_opentelemetry/)

**Comment by allisonsierra** [comment]
https://partners-intl.aliyun.com/help/en/log-service/latest/import-trace-data-from-rust-applications-to-log-service-by-using-opentelemetry-sdk-for-rust
